/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package es.gva.cit.gvmetrica.orgcasi.provider;

import es.gva.cit.gvmetrica.orgcasi.util.OrgcasiAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class OrgcasiItemProviderAdapterFactory extends OrgcasiAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection supportedTypes = new ArrayList();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public OrgcasiItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);		
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.AAplicacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AAplicacionItemProvider aAplicacionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.AAplicacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAAplicacionAdapter() {
		if (aAplicacionItemProvider == null) {
			aAplicacionItemProvider = new AAplicacionItemProvider(this);
		}

		return aAplicacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.Accion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AccionItemProvider accionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.Accion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAccionAdapter() {
		if (accionItemProvider == null) {
			accionItemProvider = new AccionItemProvider(this);
		}

		return accionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.Actor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActorItemProvider actorItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.Actor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActorAdapter() {
		if (actorItemProvider == null) {
			actorItemProvider = new ActorItemProvider(this);
		}

		return actorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.ActorFuncional} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActorFuncionalItemProvider actorFuncionalItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.ActorFuncional}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActorFuncionalAdapter() {
		if (actorFuncionalItemProvider == null) {
			actorFuncionalItemProvider = new ActorFuncionalItemProvider(this);
		}

		return actorFuncionalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.ADocumento} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ADocumentoItemProvider aDocumentoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.ADocumento}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createADocumentoAdapter() {
		if (aDocumentoItemProvider == null) {
			aDocumentoItemProvider = new ADocumentoItemProvider(this);
		}

		return aDocumentoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.ADocumentoFinal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ADocumentoFinalItemProvider aDocumentoFinalItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.ADocumentoFinal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createADocumentoFinalAdapter() {
		if (aDocumentoFinalItemProvider == null) {
			aDocumentoFinalItemProvider = new ADocumentoFinalItemProvider(this);
		}

		return aDocumentoFinalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.AEstructuraFuncional} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AEstructuraFuncionalItemProvider aEstructuraFuncionalItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.AEstructuraFuncional}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAEstructuraFuncionalAdapter() {
		if (aEstructuraFuncionalItemProvider == null) {
			aEstructuraFuncionalItemProvider = new AEstructuraFuncionalItemProvider(this);
		}

		return aEstructuraFuncionalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.AFlujo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AFlujoItemProvider aFlujoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.AFlujo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAFlujoAdapter() {
		if (aFlujoItemProvider == null) {
			aFlujoItemProvider = new AFlujoItemProvider(this);
		}

		return aFlujoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.ANormativaYLegislacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ANormativaYLegislacionItemProvider aNormativaYLegislacionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.ANormativaYLegislacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createANormativaYLegislacionAdapter() {
		if (aNormativaYLegislacionItemProvider == null) {
			aNormativaYLegislacionItemProvider = new ANormativaYLegislacionItemProvider(this);
		}

		return aNormativaYLegislacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.AOperacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AOperacionItemProvider aOperacionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.AOperacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAOperacionAdapter() {
		if (aOperacionItemProvider == null) {
			aOperacionItemProvider = new AOperacionItemProvider(this);
		}

		return aOperacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.AProcedimiento} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AProcedimientoItemProvider aProcedimientoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.AProcedimiento}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAProcedimientoAdapter() {
		if (aProcedimientoItemProvider == null) {
			aProcedimientoItemProvider = new AProcedimientoItemProvider(this);
		}

		return aProcedimientoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.ARepositorio} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ARepositorioItemProvider aRepositorioItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.ARepositorio}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createARepositorioAdapter() {
		if (aRepositorioItemProvider == null) {
			aRepositorioItemProvider = new ARepositorioItemProvider(this);
		}

		return aRepositorioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.ASubprocedimiento} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ASubprocedimientoItemProvider aSubprocedimientoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.ASubprocedimiento}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createASubprocedimientoAdapter() {
		if (aSubprocedimientoItemProvider == null) {
			aSubprocedimientoItemProvider = new ASubprocedimientoItemProvider(this);
		}

		return aSubprocedimientoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.ATerminoGlosario} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ATerminoGlosarioItemProvider aTerminoGlosarioItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.ATerminoGlosario}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createATerminoGlosarioAdapter() {
		if (aTerminoGlosarioItemProvider == null) {
			aTerminoGlosarioItemProvider = new ATerminoGlosarioItemProvider(this);
		}

		return aTerminoGlosarioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.AUnidadExterna} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AUnidadExternaItemProvider aUnidadExternaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.AUnidadExterna}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAUnidadExternaAdapter() {
		if (aUnidadExternaItemProvider == null) {
			aUnidadExternaItemProvider = new AUnidadExternaItemProvider(this);
		}

		return aUnidadExternaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.AUnidadOrganica} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AUnidadOrganicaItemProvider aUnidadOrganicaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.AUnidadOrganica}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAUnidadOrganicaAdapter() {
		if (aUnidadOrganicaItemProvider == null) {
			aUnidadOrganicaItemProvider = new AUnidadOrganicaItemProvider(this);
		}

		return aUnidadOrganicaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CAccionesSuceso} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CAccionesSucesoItemProvider cAccionesSucesoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CAccionesSuceso}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCAccionesSucesoAdapter() {
		if (cAccionesSucesoItemProvider == null) {
			cAccionesSucesoItemProvider = new CAccionesSucesoItemProvider(this);
		}

		return cAccionesSucesoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CActores} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CActoresItemProvider cActoresItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CActores}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCActoresAdapter() {
		if (cActoresItemProvider == null) {
			cActoresItemProvider = new CActoresItemProvider(this);
		}

		return cActoresItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CActoresSuceso} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CActoresSucesoItemProvider cActoresSucesoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CActoresSuceso}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCActoresSucesoAdapter() {
		if (cActoresSucesoItemProvider == null) {
			cActoresSucesoItemProvider = new CActoresSucesoItemProvider(this);
		}

		return cActoresSucesoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CampoDatos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CampoDatosItemProvider campoDatosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CampoDatos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCampoDatosAdapter() {
		if (campoDatosItemProvider == null) {
			campoDatosItemProvider = new CampoDatosItemProvider(this);
		}

		return campoDatosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CAplicaciones} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CAplicacionesItemProvider cAplicacionesItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CAplicaciones}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCAplicacionesAdapter() {
		if (cAplicacionesItemProvider == null) {
			cAplicacionesItemProvider = new CAplicacionesItemProvider(this);
		}

		return cAplicacionesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CCamposDatos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CCamposDatosItemProvider cCamposDatosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CCamposDatos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCCamposDatosAdapter() {
		if (cCamposDatosItemProvider == null) {
			cCamposDatosItemProvider = new CCamposDatosItemProvider(this);
		}

		return cCamposDatosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CDocumentos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CDocumentosItemProvider cDocumentosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CDocumentos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCDocumentosAdapter() {
		if (cDocumentosItemProvider == null) {
			cDocumentosItemProvider = new CDocumentosItemProvider(this);
		}

		return cDocumentosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CEntradasAccion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CEntradasAccionItemProvider cEntradasAccionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CEntradasAccion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCEntradasAccionAdapter() {
		if (cEntradasAccionItemProvider == null) {
			cEntradasAccionItemProvider = new CEntradasAccionItemProvider(this);
		}

		return cEntradasAccionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CEntradasSuceso} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CEntradasSucesoItemProvider cEntradasSucesoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CEntradasSuceso}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCEntradasSucesoAdapter() {
		if (cEntradasSucesoItemProvider == null) {
			cEntradasSucesoItemProvider = new CEntradasSucesoItemProvider(this);
		}

		return cEntradasSucesoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CEstructurasDatos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CEstructurasDatosItemProvider cEstructurasDatosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CEstructurasDatos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCEstructurasDatosAdapter() {
		if (cEstructurasDatosItemProvider == null) {
			cEstructurasDatosItemProvider = new CEstructurasDatosItemProvider(this);
		}

		return cEstructurasDatosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CEstructurasDatosSuceso} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CEstructurasDatosSucesoItemProvider cEstructurasDatosSucesoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CEstructurasDatosSuceso}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCEstructurasDatosSucesoAdapter() {
		if (cEstructurasDatosSucesoItemProvider == null) {
			cEstructurasDatosSucesoItemProvider = new CEstructurasDatosSucesoItemProvider(this);
		}

		return cEstructurasDatosSucesoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CFlujos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CFlujosItemProvider cFlujosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CFlujos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCFlujosAdapter() {
		if (cFlujosItemProvider == null) {
			cFlujosItemProvider = new CFlujosItemProvider(this);
		}

		return cFlujosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CFlujosSuceso} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CFlujosSucesoItemProvider cFlujosSucesoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CFlujosSuceso}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCFlujosSucesoAdapter() {
		if (cFlujosSucesoItemProvider == null) {
			cFlujosSucesoItemProvider = new CFlujosSucesoItemProvider(this);
		}

		return cFlujosSucesoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CEstructurasFuncionales} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CEstructurasFuncionalesItemProvider cEstructurasFuncionalesItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CEstructurasFuncionales}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCEstructurasFuncionalesAdapter() {
		if (cEstructurasFuncionalesItemProvider == null) {
			cEstructurasFuncionalesItemProvider = new CEstructurasFuncionalesItemProvider(this);
		}

		return cEstructurasFuncionalesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CImportacionesPor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CImportacionesPorItemProvider cImportacionesPorItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CImportacionesPor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCImportacionesPorAdapter() {
		if (cImportacionesPorItemProvider == null) {
			cImportacionesPorItemProvider = new CImportacionesPorItemProvider(this);
		}

		return cImportacionesPorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CImportacionesServicios} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CImportacionesServiciosItemProvider cImportacionesServiciosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CImportacionesServicios}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCImportacionesServiciosAdapter() {
		if (cImportacionesServiciosItemProvider == null) {
			cImportacionesServiciosItemProvider = new CImportacionesServiciosItemProvider(this);
		}

		return cImportacionesServiciosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CInterfaces} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CInterfacesItemProvider cInterfacesItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CInterfaces}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCInterfacesAdapter() {
		if (cInterfacesItemProvider == null) {
			cInterfacesItemProvider = new CInterfacesItemProvider(this);
		}

		return cInterfacesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CLibreriasServicios} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CLibreriasServiciosItemProvider cLibreriasServiciosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CLibreriasServicios}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCLibreriasServiciosAdapter() {
		if (cLibreriasServiciosItemProvider == null) {
			cLibreriasServiciosItemProvider = new CLibreriasServiciosItemProvider(this);
		}

		return cLibreriasServiciosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CNormativasYLegislaciones} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CNormativasYLegislacionesItemProvider cNormativasYLegislacionesItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CNormativasYLegislaciones}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCNormativasYLegislacionesAdapter() {
		if (cNormativasYLegislacionesItemProvider == null) {
			cNormativasYLegislacionesItemProvider = new CNormativasYLegislacionesItemProvider(this);
		}

		return cNormativasYLegislacionesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.ContenedorDatos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContenedorDatosItemProvider contenedorDatosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.ContenedorDatos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createContenedorDatosAdapter() {
		if (contenedorDatosItemProvider == null) {
			contenedorDatosItemProvider = new ContenedorDatosItemProvider(this);
		}

		return contenedorDatosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.COperaciones} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected COperacionesItemProvider cOperacionesItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.COperaciones}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCOperacionesAdapter() {
		if (cOperacionesItemProvider == null) {
			cOperacionesItemProvider = new COperacionesItemProvider(this);
		}

		return cOperacionesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CProcedimientos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CProcedimientosItemProvider cProcedimientosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CProcedimientos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCProcedimientosAdapter() {
		if (cProcedimientosItemProvider == null) {
			cProcedimientosItemProvider = new CProcedimientosItemProvider(this);
		}

		return cProcedimientosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CRelacionesDatos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CRelacionesDatosItemProvider cRelacionesDatosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CRelacionesDatos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCRelacionesDatosAdapter() {
		if (cRelacionesDatosItemProvider == null) {
			cRelacionesDatosItemProvider = new CRelacionesDatosItemProvider(this);
		}

		return cRelacionesDatosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CSalidasAccion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CSalidasAccionItemProvider cSalidasAccionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CSalidasAccion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCSalidasAccionAdapter() {
		if (cSalidasAccionItemProvider == null) {
			cSalidasAccionItemProvider = new CSalidasAccionItemProvider(this);
		}

		return cSalidasAccionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CSalidasSuceso} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CSalidasSucesoItemProvider cSalidasSucesoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CSalidasSuceso}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCSalidasSucesoAdapter() {
		if (cSalidasSucesoItemProvider == null) {
			cSalidasSucesoItemProvider = new CSalidasSucesoItemProvider(this);
		}

		return cSalidasSucesoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CServicios} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CServiciosItemProvider cServiciosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CServicios}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCServiciosAdapter() {
		if (cServiciosItemProvider == null) {
			cServiciosItemProvider = new CServiciosItemProvider(this);
		}

		return cServiciosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CServicioUsadoPorSucesos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CServicioUsadoPorSucesosItemProvider cServicioUsadoPorSucesosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CServicioUsadoPorSucesos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCServicioUsadoPorSucesosAdapter() {
		if (cServicioUsadoPorSucesosItemProvider == null) {
			cServicioUsadoPorSucesosItemProvider = new CServicioUsadoPorSucesosItemProvider(this);
		}

		return cServicioUsadoPorSucesosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CSistemas} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CSistemasItemProvider cSistemasItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CSistemas}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCSistemasAdapter() {
		if (cSistemasItemProvider == null) {
			cSistemasItemProvider = new CSistemasItemProvider(this);
		}

		return cSistemasItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CSubsistemas} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CSubsistemasItemProvider cSubsistemasItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CSubsistemas}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCSubsistemasAdapter() {
		if (cSubsistemasItemProvider == null) {
			cSubsistemasItemProvider = new CSubsistemasItemProvider(this);
		}

		return cSubsistemasItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CSucesos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CSucesosItemProvider cSucesosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CSucesos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCSucesosAdapter() {
		if (cSucesosItemProvider == null) {
			cSucesosItemProvider = new CSucesosItemProvider(this);
		}

		return cSucesosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CTerminosGlosario} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CTerminosGlosarioItemProvider cTerminosGlosarioItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CTerminosGlosario}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCTerminosGlosarioAdapter() {
		if (cTerminosGlosarioItemProvider == null) {
			cTerminosGlosarioItemProvider = new CTerminosGlosarioItemProvider(this);
		}

		return cTerminosGlosarioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CUnidades} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CUnidadesItemProvider cUnidadesItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CUnidades}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCUnidadesAdapter() {
		if (cUnidadesItemProvider == null) {
			cUnidadesItemProvider = new CUnidadesItemProvider(this);
		}

		return cUnidadesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CUnidadesExternas} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CUnidadesExternasItemProvider cUnidadesExternasItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CUnidadesExternas}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCUnidadesExternasAdapter() {
		if (cUnidadesExternasItemProvider == null) {
			cUnidadesExternasItemProvider = new CUnidadesExternasItemProvider(this);
		}

		return cUnidadesExternasItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CUnidadesOrganicas} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CUnidadesOrganicasItemProvider cUnidadesOrganicasItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CUnidadesOrganicas}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCUnidadesOrganicasAdapter() {
		if (cUnidadesOrganicasItemProvider == null) {
			cUnidadesOrganicasItemProvider = new CUnidadesOrganicasItemProvider(this);
		}

		return cUnidadesOrganicasItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CUsadoPorSubsistemas} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CUsadoPorSubsistemasItemProvider cUsadoPorSubsistemasItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CUsadoPorSubsistemas}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCUsadoPorSubsistemasAdapter() {
		if (cUsadoPorSubsistemasItemProvider == null) {
			cUsadoPorSubsistemasItemProvider = new CUsadoPorSubsistemasItemProvider(this);
		}

		return cUsadoPorSubsistemasItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CUsadoPorSucesos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CUsadoPorSucesosItemProvider cUsadoPorSucesosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CUsadoPorSucesos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCUsadoPorSucesosAdapter() {
		if (cUsadoPorSucesosItemProvider == null) {
			cUsadoPorSucesosItemProvider = new CUsadoPorSucesosItemProvider(this);
		}

		return cUsadoPorSucesosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.CUsosSubsistemas} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CUsosSubsistemasItemProvider cUsosSubsistemasItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.CUsosSubsistemas}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCUsosSubsistemasAdapter() {
		if (cUsosSubsistemasItemProvider == null) {
			cUsosSubsistemasItemProvider = new CUsosSubsistemasItemProvider(this);
		}

		return cUsosSubsistemasItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.DocumentoEnEstado} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentoEnEstadoItemProvider documentoEnEstadoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.DocumentoEnEstado}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDocumentoEnEstadoAdapter() {
		if (documentoEnEstadoItemProvider == null) {
			documentoEnEstadoItemProvider = new DocumentoEnEstadoItemProvider(this);
		}

		return documentoEnEstadoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.Entrada} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntradaItemProvider entradaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.Entrada}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createEntradaAdapter() {
		if (entradaItemProvider == null) {
			entradaItemProvider = new EntradaItemProvider(this);
		}

		return entradaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.EntradaAccion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntradaAccionItemProvider entradaAccionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.EntradaAccion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createEntradaAccionAdapter() {
		if (entradaAccionItemProvider == null) {
			entradaAccionItemProvider = new EntradaAccionItemProvider(this);
		}

		return entradaAccionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.EntradaServicio} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntradaServicioItemProvider entradaServicioItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.EntradaServicio}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createEntradaServicioAdapter() {
		if (entradaServicioItemProvider == null) {
			entradaServicioItemProvider = new EntradaServicioItemProvider(this);
		}

		return entradaServicioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.EntradaSuceso} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntradaSucesoItemProvider entradaSucesoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.EntradaSuceso}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createEntradaSucesoAdapter() {
		if (entradaSucesoItemProvider == null) {
			entradaSucesoItemProvider = new EntradaSucesoItemProvider(this);
		}

		return entradaSucesoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.EstructuraDatos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EstructuraDatosItemProvider estructuraDatosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.EstructuraDatos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createEstructuraDatosAdapter() {
		if (estructuraDatosItemProvider == null) {
			estructuraDatosItemProvider = new EstructuraDatosItemProvider(this);
		}

		return estructuraDatosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.ImportacionServicios} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImportacionServiciosItemProvider importacionServiciosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.ImportacionServicios}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createImportacionServiciosAdapter() {
		if (importacionServiciosItemProvider == null) {
			importacionServiciosItemProvider = new ImportacionServiciosItemProvider(this);
		}

		return importacionServiciosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.Interfaz} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfazItemProvider interfazItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.Interfaz}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInterfazAdapter() {
		if (interfazItemProvider == null) {
			interfazItemProvider = new InterfazItemProvider(this);
		}

		return interfazItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.LibreriaServicios} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LibreriaServiciosItemProvider libreriaServiciosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.LibreriaServicios}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createLibreriaServiciosAdapter() {
		if (libreriaServiciosItemProvider == null) {
			libreriaServiciosItemProvider = new LibreriaServiciosItemProvider(this);
		}

		return libreriaServiciosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.MiembroRelacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MiembroRelacionItemProvider miembroRelacionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.MiembroRelacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createMiembroRelacionAdapter() {
		if (miembroRelacionItemProvider == null) {
			miembroRelacionItemProvider = new MiembroRelacionItemProvider(this);
		}

		return miembroRelacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.OrgcasiObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrgcasiObjectItemProvider orgcasiObjectItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.OrgcasiObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createOrgcasiObjectAdapter() {
		if (orgcasiObjectItemProvider == null) {
			orgcasiObjectItemProvider = new OrgcasiObjectItemProvider(this);
		}

		return orgcasiObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.RelacionDatos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelacionDatosItemProvider relacionDatosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.RelacionDatos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRelacionDatosAdapter() {
		if (relacionDatosItemProvider == null) {
			relacionDatosItemProvider = new RelacionDatosItemProvider(this);
		}

		return relacionDatosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.RolSolicitante} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RolSolicitanteItemProvider rolSolicitanteItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.RolSolicitante}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRolSolicitanteAdapter() {
		if (rolSolicitanteItemProvider == null) {
			rolSolicitanteItemProvider = new RolSolicitanteItemProvider(this);
		}

		return rolSolicitanteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.RolSolicitado} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RolSolicitadoItemProvider rolSolicitadoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.RolSolicitado}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRolSolicitadoAdapter() {
		if (rolSolicitadoItemProvider == null) {
			rolSolicitadoItemProvider = new RolSolicitadoItemProvider(this);
		}

		return rolSolicitadoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.Salida} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SalidaItemProvider salidaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.Salida}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSalidaAdapter() {
		if (salidaItemProvider == null) {
			salidaItemProvider = new SalidaItemProvider(this);
		}

		return salidaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.SalidaAccion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SalidaAccionItemProvider salidaAccionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.SalidaAccion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSalidaAccionAdapter() {
		if (salidaAccionItemProvider == null) {
			salidaAccionItemProvider = new SalidaAccionItemProvider(this);
		}

		return salidaAccionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.SalidaServicio} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SalidaServicioItemProvider salidaServicioItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.SalidaServicio}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSalidaServicioAdapter() {
		if (salidaServicioItemProvider == null) {
			salidaServicioItemProvider = new SalidaServicioItemProvider(this);
		}

		return salidaServicioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.SalidaSuceso} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SalidaSucesoItemProvider salidaSucesoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.SalidaSuceso}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSalidaSucesoAdapter() {
		if (salidaSucesoItemProvider == null) {
			salidaSucesoItemProvider = new SalidaSucesoItemProvider(this);
		}

		return salidaSucesoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.Servicio} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServicioItemProvider servicioItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.Servicio}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createServicioAdapter() {
		if (servicioItemProvider == null) {
			servicioItemProvider = new ServicioItemProvider(this);
		}

		return servicioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.Sistema} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SistemaItemProvider sistemaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.Sistema}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSistemaAdapter() {
		if (sistemaItemProvider == null) {
			sistemaItemProvider = new SistemaItemProvider(this);
		}

		return sistemaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.Subsistema} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubsistemaItemProvider subsistemaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.Subsistema}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSubsistemaAdapter() {
		if (subsistemaItemProvider == null) {
			subsistemaItemProvider = new SubsistemaItemProvider(this);
		}

		return subsistemaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.SucesoConstructor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SucesoConstructorItemProvider sucesoConstructorItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.SucesoConstructor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSucesoConstructorAdapter() {
		if (sucesoConstructorItemProvider == null) {
			sucesoConstructorItemProvider = new SucesoConstructorItemProvider(this);
		}

		return sucesoConstructorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.SucesoConsultor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SucesoConsultorItemProvider sucesoConsultorItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.SucesoConsultor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSucesoConsultorAdapter() {
		if (sucesoConsultorItemProvider == null) {
			sucesoConsultorItemProvider = new SucesoConsultorItemProvider(this);
		}

		return sucesoConsultorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.UsoServicio} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UsoServicioItemProvider usoServicioItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.UsoServicio}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUsoServicioAdapter() {
		if (usoServicioItemProvider == null) {
			usoServicioItemProvider = new UsoServicioItemProvider(this);
		}

		return usoServicioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.UsoSubsistema} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UsoSubsistemaItemProvider usoSubsistemaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.UsoSubsistema}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUsoSubsistemaAdapter() {
		if (usoSubsistemaItemProvider == null) {
			usoSubsistemaItemProvider = new UsoSubsistemaItemProvider(this);
		}

		return usoSubsistemaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.orgcasi.UsoSuceso} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UsoSucesoItemProvider usoSucesoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.orgcasi.UsoSuceso}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUsoSucesoAdapter() {
		if (usoSucesoItemProvider == null) {
			usoSucesoItemProvider = new UsoSucesoItemProvider(this);
		}

		return usoSucesoItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class) || (((Class)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (aAplicacionItemProvider != null) aAplicacionItemProvider.dispose();
		if (accionItemProvider != null) accionItemProvider.dispose();
		if (actorItemProvider != null) actorItemProvider.dispose();
		if (actorFuncionalItemProvider != null) actorFuncionalItemProvider.dispose();
		if (aDocumentoItemProvider != null) aDocumentoItemProvider.dispose();
		if (aDocumentoFinalItemProvider != null) aDocumentoFinalItemProvider.dispose();
		if (aEstructuraFuncionalItemProvider != null) aEstructuraFuncionalItemProvider.dispose();
		if (aFlujoItemProvider != null) aFlujoItemProvider.dispose();
		if (aNormativaYLegislacionItemProvider != null) aNormativaYLegislacionItemProvider.dispose();
		if (aOperacionItemProvider != null) aOperacionItemProvider.dispose();
		if (aProcedimientoItemProvider != null) aProcedimientoItemProvider.dispose();
		if (aRepositorioItemProvider != null) aRepositorioItemProvider.dispose();
		if (aSubprocedimientoItemProvider != null) aSubprocedimientoItemProvider.dispose();
		if (aTerminoGlosarioItemProvider != null) aTerminoGlosarioItemProvider.dispose();
		if (aUnidadExternaItemProvider != null) aUnidadExternaItemProvider.dispose();
		if (aUnidadOrganicaItemProvider != null) aUnidadOrganicaItemProvider.dispose();
		if (cAccionesSucesoItemProvider != null) cAccionesSucesoItemProvider.dispose();
		if (cActoresItemProvider != null) cActoresItemProvider.dispose();
		if (cActoresSucesoItemProvider != null) cActoresSucesoItemProvider.dispose();
		if (campoDatosItemProvider != null) campoDatosItemProvider.dispose();
		if (cAplicacionesItemProvider != null) cAplicacionesItemProvider.dispose();
		if (cCamposDatosItemProvider != null) cCamposDatosItemProvider.dispose();
		if (cDocumentosItemProvider != null) cDocumentosItemProvider.dispose();
		if (cEntradasAccionItemProvider != null) cEntradasAccionItemProvider.dispose();
		if (cEntradasSucesoItemProvider != null) cEntradasSucesoItemProvider.dispose();
		if (cEstructurasDatosItemProvider != null) cEstructurasDatosItemProvider.dispose();
		if (cEstructurasDatosSucesoItemProvider != null) cEstructurasDatosSucesoItemProvider.dispose();
		if (cFlujosItemProvider != null) cFlujosItemProvider.dispose();
		if (cFlujosSucesoItemProvider != null) cFlujosSucesoItemProvider.dispose();
		if (cEstructurasFuncionalesItemProvider != null) cEstructurasFuncionalesItemProvider.dispose();
		if (cImportacionesPorItemProvider != null) cImportacionesPorItemProvider.dispose();
		if (cImportacionesServiciosItemProvider != null) cImportacionesServiciosItemProvider.dispose();
		if (cInterfacesItemProvider != null) cInterfacesItemProvider.dispose();
		if (cLibreriasServiciosItemProvider != null) cLibreriasServiciosItemProvider.dispose();
		if (cNormativasYLegislacionesItemProvider != null) cNormativasYLegislacionesItemProvider.dispose();
		if (contenedorDatosItemProvider != null) contenedorDatosItemProvider.dispose();
		if (cOperacionesItemProvider != null) cOperacionesItemProvider.dispose();
		if (cProcedimientosItemProvider != null) cProcedimientosItemProvider.dispose();
		if (cRelacionesDatosItemProvider != null) cRelacionesDatosItemProvider.dispose();
		if (cSalidasAccionItemProvider != null) cSalidasAccionItemProvider.dispose();
		if (cSalidasSucesoItemProvider != null) cSalidasSucesoItemProvider.dispose();
		if (cServiciosItemProvider != null) cServiciosItemProvider.dispose();
		if (cServicioUsadoPorSucesosItemProvider != null) cServicioUsadoPorSucesosItemProvider.dispose();
		if (cSistemasItemProvider != null) cSistemasItemProvider.dispose();
		if (cSubsistemasItemProvider != null) cSubsistemasItemProvider.dispose();
		if (cSucesosItemProvider != null) cSucesosItemProvider.dispose();
		if (cTerminosGlosarioItemProvider != null) cTerminosGlosarioItemProvider.dispose();
		if (cUnidadesItemProvider != null) cUnidadesItemProvider.dispose();
		if (cUnidadesExternasItemProvider != null) cUnidadesExternasItemProvider.dispose();
		if (cUnidadesOrganicasItemProvider != null) cUnidadesOrganicasItemProvider.dispose();
		if (cUsadoPorSubsistemasItemProvider != null) cUsadoPorSubsistemasItemProvider.dispose();
		if (cUsadoPorSucesosItemProvider != null) cUsadoPorSucesosItemProvider.dispose();
		if (cUsosSubsistemasItemProvider != null) cUsosSubsistemasItemProvider.dispose();
		if (documentoEnEstadoItemProvider != null) documentoEnEstadoItemProvider.dispose();
		if (entradaItemProvider != null) entradaItemProvider.dispose();
		if (entradaAccionItemProvider != null) entradaAccionItemProvider.dispose();
		if (entradaServicioItemProvider != null) entradaServicioItemProvider.dispose();
		if (entradaSucesoItemProvider != null) entradaSucesoItemProvider.dispose();
		if (estructuraDatosItemProvider != null) estructuraDatosItemProvider.dispose();
		if (importacionServiciosItemProvider != null) importacionServiciosItemProvider.dispose();
		if (interfazItemProvider != null) interfazItemProvider.dispose();
		if (libreriaServiciosItemProvider != null) libreriaServiciosItemProvider.dispose();
		if (miembroRelacionItemProvider != null) miembroRelacionItemProvider.dispose();
		if (orgcasiObjectItemProvider != null) orgcasiObjectItemProvider.dispose();
		if (relacionDatosItemProvider != null) relacionDatosItemProvider.dispose();
		if (rolSolicitanteItemProvider != null) rolSolicitanteItemProvider.dispose();
		if (rolSolicitadoItemProvider != null) rolSolicitadoItemProvider.dispose();
		if (salidaItemProvider != null) salidaItemProvider.dispose();
		if (salidaAccionItemProvider != null) salidaAccionItemProvider.dispose();
		if (salidaServicioItemProvider != null) salidaServicioItemProvider.dispose();
		if (salidaSucesoItemProvider != null) salidaSucesoItemProvider.dispose();
		if (servicioItemProvider != null) servicioItemProvider.dispose();
		if (sistemaItemProvider != null) sistemaItemProvider.dispose();
		if (subsistemaItemProvider != null) subsistemaItemProvider.dispose();
		if (sucesoConstructorItemProvider != null) sucesoConstructorItemProvider.dispose();
		if (sucesoConsultorItemProvider != null) sucesoConsultorItemProvider.dispose();
		if (usoServicioItemProvider != null) usoServicioItemProvider.dispose();
		if (usoSubsistemaItemProvider != null) usoSubsistemaItemProvider.dispose();
		if (usoSucesoItemProvider != null) usoSucesoItemProvider.dispose();
	}

}
