/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package es.gva.cit.simapa.provider;

import es.gva.cit.simapa.util.SimapaAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class SimapaItemProviderAdapterFactory extends SimapaAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection supportedTypes = new ArrayList();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SimapaItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);		
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.Repositorio} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepositorioItemProvider repositorioItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.Repositorio}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRepositorioAdapter() {
		if (repositorioItemProvider == null) {
			repositorioItemProvider = new RepositorioItemProvider(this);
		}

		return repositorioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.NormativasYLegislaciones} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NormativasYLegislacionesItemProvider normativasYLegislacionesItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.NormativasYLegislaciones}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createNormativasYLegislacionesAdapter() {
		if (normativasYLegislacionesItemProvider == null) {
			normativasYLegislacionesItemProvider = new NormativasYLegislacionesItemProvider(this);
		}

		return normativasYLegislacionesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.NormativaYLegislacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NormativaYLegislacionItemProvider normativaYLegislacionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.NormativaYLegislacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createNormativaYLegislacionAdapter() {
		if (normativaYLegislacionItemProvider == null) {
			normativaYLegislacionItemProvider = new NormativaYLegislacionItemProvider(this);
		}

		return normativaYLegislacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.UnidadesOrganicas} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnidadesOrganicasItemProvider unidadesOrganicasItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.UnidadesOrganicas}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUnidadesOrganicasAdapter() {
		if (unidadesOrganicasItemProvider == null) {
			unidadesOrganicasItemProvider = new UnidadesOrganicasItemProvider(this);
		}

		return unidadesOrganicasItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.UnidadOrganica} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnidadOrganicaItemProvider unidadOrganicaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.UnidadOrganica}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUnidadOrganicaAdapter() {
		if (unidadOrganicaItemProvider == null) {
			unidadOrganicaItemProvider = new UnidadOrganicaItemProvider(this);
		}

		return unidadOrganicaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.UnidadesExternas} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnidadesExternasItemProvider unidadesExternasItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.UnidadesExternas}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUnidadesExternasAdapter() {
		if (unidadesExternasItemProvider == null) {
			unidadesExternasItemProvider = new UnidadesExternasItemProvider(this);
		}

		return unidadesExternasItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.UnidadExterna} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnidadExternaItemProvider unidadExternaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.UnidadExterna}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUnidadExternaAdapter() {
		if (unidadExternaItemProvider == null) {
			unidadExternaItemProvider = new UnidadExternaItemProvider(this);
		}

		return unidadExternaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.EstructurasFuncionales} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EstructurasFuncionalesItemProvider estructurasFuncionalesItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.EstructurasFuncionales}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createEstructurasFuncionalesAdapter() {
		if (estructurasFuncionalesItemProvider == null) {
			estructurasFuncionalesItemProvider = new EstructurasFuncionalesItemProvider(this);
		}

		return estructurasFuncionalesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.EstructuraFuncional} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EstructuraFuncionalItemProvider estructuraFuncionalItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.EstructuraFuncional}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createEstructuraFuncionalAdapter() {
		if (estructuraFuncionalItemProvider == null) {
			estructuraFuncionalItemProvider = new EstructuraFuncionalItemProvider(this);
		}

		return estructuraFuncionalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.ClasesDocumento} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClasesDocumentoItemProvider clasesDocumentoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.ClasesDocumento}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createClasesDocumentoAdapter() {
		if (clasesDocumentoItemProvider == null) {
			clasesDocumentoItemProvider = new ClasesDocumentoItemProvider(this);
		}

		return clasesDocumentoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.ClaseDocumento} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClaseDocumentoItemProvider claseDocumentoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.ClaseDocumento}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createClaseDocumentoAdapter() {
		if (claseDocumentoItemProvider == null) {
			claseDocumentoItemProvider = new ClaseDocumentoItemProvider(this);
		}

		return claseDocumentoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.Documentos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentosItemProvider documentosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.Documentos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDocumentosAdapter() {
		if (documentosItemProvider == null) {
			documentosItemProvider = new DocumentosItemProvider(this);
		}

		return documentosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.Documento} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentoItemProvider documentoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.Documento}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDocumentoAdapter() {
		if (documentoItemProvider == null) {
			documentoItemProvider = new DocumentoItemProvider(this);
		}

		return documentoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.Aplicaciones} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AplicacionesItemProvider aplicacionesItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.Aplicaciones}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAplicacionesAdapter() {
		if (aplicacionesItemProvider == null) {
			aplicacionesItemProvider = new AplicacionesItemProvider(this);
		}

		return aplicacionesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.Aplicacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AplicacionItemProvider aplicacionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.Aplicacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAplicacionAdapter() {
		if (aplicacionItemProvider == null) {
			aplicacionItemProvider = new AplicacionItemProvider(this);
		}

		return aplicacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.Glosario} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GlosarioItemProvider glosarioItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.Glosario}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createGlosarioAdapter() {
		if (glosarioItemProvider == null) {
			glosarioItemProvider = new GlosarioItemProvider(this);
		}

		return glosarioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.TerminoGlosario} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TerminoGlosarioItemProvider terminoGlosarioItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.TerminoGlosario}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTerminoGlosarioAdapter() {
		if (terminoGlosarioItemProvider == null) {
			terminoGlosarioItemProvider = new TerminoGlosarioItemProvider(this);
		}

		return terminoGlosarioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.Procedimientos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProcedimientosItemProvider procedimientosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.Procedimientos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createProcedimientosAdapter() {
		if (procedimientosItemProvider == null) {
			procedimientosItemProvider = new ProcedimientosItemProvider(this);
		}

		return procedimientosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.Procedimiento} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProcedimientoItemProvider procedimientoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.Procedimiento}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createProcedimientoAdapter() {
		if (procedimientoItemProvider == null) {
			procedimientoItemProvider = new ProcedimientoItemProvider(this);
		}

		return procedimientoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.FichaArchivistica} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FichaArchivisticaItemProvider fichaArchivisticaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.FichaArchivistica}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFichaArchivisticaAdapter() {
		if (fichaArchivisticaItemProvider == null) {
			fichaArchivisticaItemProvider = new FichaArchivisticaItemProvider(this);
		}

		return fichaArchivisticaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.Convocatoria} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConvocatoriaItemProvider convocatoriaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.Convocatoria}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createConvocatoriaAdapter() {
		if (convocatoriaItemProvider == null) {
			convocatoriaItemProvider = new ConvocatoriaItemProvider(this);
		}

		return convocatoriaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.ControlProcedimiento} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ControlProcedimientoItemProvider controlProcedimientoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.ControlProcedimiento}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createControlProcedimientoAdapter() {
		if (controlProcedimientoItemProvider == null) {
			controlProcedimientoItemProvider = new ControlProcedimientoItemProvider(this);
		}

		return controlProcedimientoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.TramitacionProcedimiento} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TramitacionProcedimientoItemProvider tramitacionProcedimientoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.TramitacionProcedimiento}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTramitacionProcedimientoAdapter() {
		if (tramitacionProcedimientoItemProvider == null) {
			tramitacionProcedimientoItemProvider = new TramitacionProcedimientoItemProvider(this);
		}

		return tramitacionProcedimientoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.Operaciones} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperacionesItemProvider operacionesItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.Operaciones}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createOperacionesAdapter() {
		if (operacionesItemProvider == null) {
			operacionesItemProvider = new OperacionesItemProvider(this);
		}

		return operacionesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.Operacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperacionItemProvider operacionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.Operacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createOperacionAdapter() {
		if (operacionItemProvider == null) {
			operacionItemProvider = new OperacionItemProvider(this);
		}

		return operacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.Decision} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DecisionItemProvider decisionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.Decision}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDecisionAdapter() {
		if (decisionItemProvider == null) {
			decisionItemProvider = new DecisionItemProvider(this);
		}

		return decisionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.Subprocedimiento} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubprocedimientoItemProvider subprocedimientoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.Subprocedimiento}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSubprocedimientoAdapter() {
		if (subprocedimientoItemProvider == null) {
			subprocedimientoItemProvider = new SubprocedimientoItemProvider(this);
		}

		return subprocedimientoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.DocumentoFinalInterno} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentoFinalInternoItemProvider documentoFinalInternoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.DocumentoFinalInterno}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDocumentoFinalInternoAdapter() {
		if (documentoFinalInternoItemProvider == null) {
			documentoFinalInternoItemProvider = new DocumentoFinalInternoItemProvider(this);
		}

		return documentoFinalInternoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.EntradaDocumentoFinal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntradaDocumentoFinalItemProvider entradaDocumentoFinalItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.EntradaDocumentoFinal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createEntradaDocumentoFinalAdapter() {
		if (entradaDocumentoFinalItemProvider == null) {
			entradaDocumentoFinalItemProvider = new EntradaDocumentoFinalItemProvider(this);
		}

		return entradaDocumentoFinalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.SalidaDocumentoFinal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SalidaDocumentoFinalItemProvider salidaDocumentoFinalItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.SalidaDocumentoFinal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSalidaDocumentoFinalAdapter() {
		if (salidaDocumentoFinalItemProvider == null) {
			salidaDocumentoFinalItemProvider = new SalidaDocumentoFinalItemProvider(this);
		}

		return salidaDocumentoFinalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.SimapaCollection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SimapaCollectionItemProvider simapaCollectionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.SimapaCollection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSimapaCollectionAdapter() {
		if (simapaCollectionItemProvider == null) {
			simapaCollectionItemProvider = new SimapaCollectionItemProvider(this);
		}

		return simapaCollectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.FinProceso} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FinProcesoItemProvider finProcesoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.FinProceso}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFinProcesoAdapter() {
		if (finProcesoItemProvider == null) {
			finProcesoItemProvider = new FinProcesoItemProvider(this);
		}

		return finProcesoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.simapa.Flujo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FlujoItemProvider flujoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.simapa.Flujo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFlujoAdapter() {
		if (flujoItemProvider == null) {
			flujoItemProvider = new FlujoItemProvider(this);
		}

		return flujoItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class) || (((Class)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (aplicacionItemProvider != null) aplicacionItemProvider.dispose();
		if (aplicacionesItemProvider != null) aplicacionesItemProvider.dispose();
		if (claseDocumentoItemProvider != null) claseDocumentoItemProvider.dispose();
		if (clasesDocumentoItemProvider != null) clasesDocumentoItemProvider.dispose();
		if (controlProcedimientoItemProvider != null) controlProcedimientoItemProvider.dispose();
		if (convocatoriaItemProvider != null) convocatoriaItemProvider.dispose();
		if (decisionItemProvider != null) decisionItemProvider.dispose();
		if (documentoItemProvider != null) documentoItemProvider.dispose();
		if (documentosItemProvider != null) documentosItemProvider.dispose();
		if (documentoFinalInternoItemProvider != null) documentoFinalInternoItemProvider.dispose();
		if (entradaDocumentoFinalItemProvider != null) entradaDocumentoFinalItemProvider.dispose();
		if (estructuraFuncionalItemProvider != null) estructuraFuncionalItemProvider.dispose();
		if (estructurasFuncionalesItemProvider != null) estructurasFuncionalesItemProvider.dispose();
		if (fichaArchivisticaItemProvider != null) fichaArchivisticaItemProvider.dispose();
		if (finProcesoItemProvider != null) finProcesoItemProvider.dispose();
		if (flujoItemProvider != null) flujoItemProvider.dispose();
		if (glosarioItemProvider != null) glosarioItemProvider.dispose();
		if (normativasYLegislacionesItemProvider != null) normativasYLegislacionesItemProvider.dispose();
		if (normativaYLegislacionItemProvider != null) normativaYLegislacionItemProvider.dispose();
		if (operacionItemProvider != null) operacionItemProvider.dispose();
		if (operacionesItemProvider != null) operacionesItemProvider.dispose();
		if (procedimientoItemProvider != null) procedimientoItemProvider.dispose();
		if (procedimientosItemProvider != null) procedimientosItemProvider.dispose();
		if (repositorioItemProvider != null) repositorioItemProvider.dispose();
		if (salidaDocumentoFinalItemProvider != null) salidaDocumentoFinalItemProvider.dispose();
		if (simapaCollectionItemProvider != null) simapaCollectionItemProvider.dispose();
		if (subprocedimientoItemProvider != null) subprocedimientoItemProvider.dispose();
		if (terminoGlosarioItemProvider != null) terminoGlosarioItemProvider.dispose();
		if (tramitacionProcedimientoItemProvider != null) tramitacionProcedimientoItemProvider.dispose();
		if (unidadesOrganicasItemProvider != null) unidadesOrganicasItemProvider.dispose();
		if (unidadOrganicaItemProvider != null) unidadOrganicaItemProvider.dispose();
		if (unidadesExternasItemProvider != null) unidadesExternasItemProvider.dispose();
		if (unidadExternaItemProvider != null) unidadExternaItemProvider.dispose();
	}

}
