/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package es.gva.cit.gvmetrica.proinso.provider;

import es.gva.cit.gvmetrica.proinso.util.ProinsoAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ProinsoItemProviderAdapterFactory extends ProinsoAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static final String copyright = "Copyright Conselleria d'Infraestructures i Transport - Generalitat Valenciana 2006";

	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection supportedTypes = new ArrayList();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ProinsoItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);		
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Actividad} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActividadItemProvider actividadItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Actividad}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActividadAdapter() {
		if (actividadItemProvider == null) {
			actividadItemProvider = new ActividadItemProvider(this);
		}

		return actividadItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.ActividadAbstracta} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActividadAbstractaItemProvider actividadAbstractaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.ActividadAbstracta}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActividadAbstractaAdapter() {
		if (actividadAbstractaItemProvider == null) {
			actividadAbstractaItemProvider = new ActividadAbstractaItemProvider(this);
		}

		return actividadAbstractaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.ActividadInterfaz} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActividadInterfazItemProvider actividadInterfazItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.ActividadInterfaz}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createActividadInterfazAdapter() {
		if (actividadInterfazItemProvider == null) {
			actividadInterfazItemProvider = new ActividadInterfazItemProvider(this);
		}

		return actividadInterfazItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Cargo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CargoItemProvider cargoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Cargo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createCargoAdapter() {
		if (cargoItemProvider == null) {
			cargoItemProvider = new CargoItemProvider(this);
		}

		return cargoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Comite} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComiteItemProvider comiteItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Comite}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createComiteAdapter() {
		if (comiteItemProvider == null) {
			comiteItemProvider = new ComiteItemProvider(this);
		}

		return comiteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Documentacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentacionItemProvider documentacionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Documentacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDocumentacionAdapter() {
		if (documentacionItemProvider == null) {
			documentacionItemProvider = new DocumentacionItemProvider(this);
		}

		return documentacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Entrada} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntradaItemProvider entradaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Entrada}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createEntradaAdapter() {
		if (entradaItemProvider == null) {
			entradaItemProvider = new EntradaItemProvider(this);
		}

		return entradaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Interfaces} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfacesItemProvider interfacesItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Interfaces}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInterfacesAdapter() {
		if (interfacesItemProvider == null) {
			interfacesItemProvider = new InterfacesItemProvider(this);
		}

		return interfacesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Interfaz} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfazItemProvider interfazItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Interfaz}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createInterfazAdapter() {
		if (interfazItemProvider == null) {
			interfazItemProvider = new InterfazItemProvider(this);
		}

		return interfazItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Metodologia} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetodologiaItemProvider metodologiaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Metodologia}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createMetodologiaAdapter() {
		if (metodologiaItemProvider == null) {
			metodologiaItemProvider = new MetodologiaItemProvider(this);
		}

		return metodologiaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Parrafo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParrafoItemProvider parrafoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Parrafo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createParrafoAdapter() {
		if (parrafoItemProvider == null) {
			parrafoItemProvider = new ParrafoItemProvider(this);
		}

		return parrafoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Participacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParticipacionItemProvider participacionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Participacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createParticipacionAdapter() {
		if (participacionItemProvider == null) {
			participacionItemProvider = new ParticipacionItemProvider(this);
		}

		return participacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.PerfilesParticipantes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PerfilesParticipantesItemProvider perfilesParticipantesItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.PerfilesParticipantes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPerfilesParticipantesAdapter() {
		if (perfilesParticipantesItemProvider == null) {
			perfilesParticipantesItemProvider = new PerfilesParticipantesItemProvider(this);
		}

		return perfilesParticipantesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.PerfilParticipante} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PerfilParticipanteItemProvider perfilParticipanteItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.PerfilParticipante}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPerfilParticipanteAdapter() {
		if (perfilParticipanteItemProvider == null) {
			perfilParticipanteItemProvider = new PerfilParticipanteItemProvider(this);
		}

		return perfilParticipanteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Practica} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PracticaItemProvider practicaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Practica}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPracticaAdapter() {
		if (practicaItemProvider == null) {
			practicaItemProvider = new PracticaItemProvider(this);
		}

		return practicaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Practicas} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PracticasItemProvider practicasItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Practicas}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createPracticasAdapter() {
		if (practicasItemProvider == null) {
			practicasItemProvider = new PracticasItemProvider(this);
		}

		return practicasItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Proceso} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProcesoItemProvider procesoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Proceso}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createProcesoAdapter() {
		if (procesoItemProvider == null) {
			procesoItemProvider = new ProcesoItemProvider(this);
		}

		return procesoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.ProcesoInterfaz} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProcesoInterfazItemProvider procesoInterfazItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.ProcesoInterfaz}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createProcesoInterfazAdapter() {
		if (procesoInterfazItemProvider == null) {
			procesoInterfazItemProvider = new ProcesoInterfazItemProvider(this);
		}

		return procesoInterfazItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Procesos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProcesosItemProvider procesosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Procesos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createProcesosAdapter() {
		if (procesosItemProvider == null) {
			procesosItemProvider = new ProcesosItemProvider(this);
		}

		return procesosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Producto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProductoItemProvider productoItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Producto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createProductoAdapter() {
		if (productoItemProvider == null) {
			productoItemProvider = new ProductoItemProvider(this);
		}

		return productoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Productos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProductosItemProvider productosItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Productos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createProductosAdapter() {
		if (productosItemProvider == null) {
			productosItemProvider = new ProductosItemProvider(this);
		}

		return productosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.ReferenceRun} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferenceRunItemProvider referenceRunItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.ReferenceRun}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createReferenceRunAdapter() {
		if (referenceRunItemProvider == null) {
			referenceRunItemProvider = new ReferenceRunItemProvider(this);
		}

		return referenceRunItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Repositorio} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepositorioItemProvider repositorioItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Repositorio}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createRepositorioAdapter() {
		if (repositorioItemProvider == null) {
			repositorioItemProvider = new RepositorioItemProvider(this);
		}

		return repositorioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Salida} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SalidaItemProvider salidaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Salida}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSalidaAdapter() {
		if (salidaItemProvider == null) {
			salidaItemProvider = new SalidaItemProvider(this);
		}

		return salidaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Seccion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SeccionItemProvider seccionItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Seccion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSeccionAdapter() {
		if (seccionItemProvider == null) {
			seccionItemProvider = new SeccionItemProvider(this);
		}

		return seccionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Tarea} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TareaItemProvider tareaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Tarea}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTareaAdapter() {
		if (tareaItemProvider == null) {
			tareaItemProvider = new TareaItemProvider(this);
		}

		return tareaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Tecnica} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TecnicaItemProvider tecnicaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Tecnica}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTecnicaAdapter() {
		if (tecnicaItemProvider == null) {
			tecnicaItemProvider = new TecnicaItemProvider(this);
		}

		return tecnicaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.Tecnicas} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TecnicasItemProvider tecnicasItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.Tecnicas}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTecnicasAdapter() {
		if (tecnicasItemProvider == null) {
			tecnicasItemProvider = new TecnicasItemProvider(this);
		}

		return tecnicasItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.TextRun} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextRunItemProvider textRunItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.TextRun}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTextRunAdapter() {
		if (textRunItemProvider == null) {
			textRunItemProvider = new TextRunItemProvider(this);
		}

		return textRunItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.UsoPractica} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UsoPracticaItemProvider usoPracticaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.UsoPractica}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUsoPracticaAdapter() {
		if (usoPracticaItemProvider == null) {
			usoPracticaItemProvider = new UsoPracticaItemProvider(this);
		}

		return usoPracticaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link es.gva.cit.gvmetrica.proinso.UsoTecnica} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UsoTecnicaItemProvider usoTecnicaItemProvider;

	/**
	 * This creates an adapter for a {@link es.gva.cit.gvmetrica.proinso.UsoTecnica}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createUsoTecnicaAdapter() {
		if (usoTecnicaItemProvider == null) {
			usoTecnicaItemProvider = new UsoTecnicaItemProvider(this);
		}

		return usoTecnicaItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class) || (((Class)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (actividadItemProvider != null) actividadItemProvider.dispose();
		if (actividadAbstractaItemProvider != null) actividadAbstractaItemProvider.dispose();
		if (actividadInterfazItemProvider != null) actividadInterfazItemProvider.dispose();
		if (cargoItemProvider != null) cargoItemProvider.dispose();
		if (comiteItemProvider != null) comiteItemProvider.dispose();
		if (documentacionItemProvider != null) documentacionItemProvider.dispose();
		if (entradaItemProvider != null) entradaItemProvider.dispose();
		if (interfacesItemProvider != null) interfacesItemProvider.dispose();
		if (interfazItemProvider != null) interfazItemProvider.dispose();
		if (metodologiaItemProvider != null) metodologiaItemProvider.dispose();
		if (parrafoItemProvider != null) parrafoItemProvider.dispose();
		if (participacionItemProvider != null) participacionItemProvider.dispose();
		if (perfilesParticipantesItemProvider != null) perfilesParticipantesItemProvider.dispose();
		if (perfilParticipanteItemProvider != null) perfilParticipanteItemProvider.dispose();
		if (practicaItemProvider != null) practicaItemProvider.dispose();
		if (practicasItemProvider != null) practicasItemProvider.dispose();
		if (procesoItemProvider != null) procesoItemProvider.dispose();
		if (procesoInterfazItemProvider != null) procesoInterfazItemProvider.dispose();
		if (procesosItemProvider != null) procesosItemProvider.dispose();
		if (productoItemProvider != null) productoItemProvider.dispose();
		if (productosItemProvider != null) productosItemProvider.dispose();
		if (referenceRunItemProvider != null) referenceRunItemProvider.dispose();
		if (repositorioItemProvider != null) repositorioItemProvider.dispose();
		if (salidaItemProvider != null) salidaItemProvider.dispose();
		if (seccionItemProvider != null) seccionItemProvider.dispose();
		if (tareaItemProvider != null) tareaItemProvider.dispose();
		if (tecnicaItemProvider != null) tecnicaItemProvider.dispose();
		if (tecnicasItemProvider != null) tecnicasItemProvider.dispose();
		if (textRunItemProvider != null) textRunItemProvider.dispose();
		if (usoPracticaItemProvider != null) usoPracticaItemProvider.dispose();
		if (usoTecnicaItemProvider != null) usoTecnicaItemProvider.dispose();
	}

}
